version: '3.8'

services:
  apache:
    image: httpd
    ports:
    - "5000:80"
    volumes:
    - /compose/apache/html:/usr/local/apache2/htdocs
    networks:
    - minha-rede

networks:
  minha-rede:
    driver: bridge
